### PR TITLE
Extended color formats & added link type and icon

### PR DESCRIPTION
**Pull request by edelvarden**
- Added link type and icon
image

- Extended hex format to support alpha channel, eg.,  `#8cb93a30`
- Show color instead of icon
- Added support for the following color formats:

  hsl(77, 69%, 80%)
  hsla(239, 66%, 75%, 0.544)
  rgb(169, 239, 193)
  rgba(168, 187, 239, 0.868)
  hwb(307 66% 6%)
  hwb(86 66% 6% / 0.732)

image

### CODE REVIEW

**Comment by edelvarden** [comment]
- Simplified from search tab to search bar

image

- Added husky for pre-commit script  and recommended prettier config, you can change it later as you wish

**Comment by edelvarden** [comment]
Also, how you look at making hotkeys always available by modifier, eg., on `Ctrl`. 
I'm not familiar with your hotkeys algorithm, but it can be good improvement.
I suggest adding it to the search bar input:

```tsx
onblur={(e) => e.target.focus()}
```

to make it always in focus for typing search queries, and additionally make hotkeys available with the modifier, it can solve this issue https://github.com/tauri-apps/global-hotkey/issues/33 because static hotkeys with modifier don't require register and unregister each time

**Comment by 0-don** [comment]
Thank you for your pull request; I have incorporated some changes as well.

There is an issue with the global_hotkey library (https://github.com/tauri-apps/global-hotkey) which prevents the registered hotkeys from functioning, hence the separate tab for search. However, I have now enabled the search functionality within the starred clipboards tab as well, and have ensured that hotkeys are disabled when you switch tabs, whether via hotkey or a click. This workaround allows for the release of the key you are typing. Until the core issue is resolved, this modification will allow for search functionality across the tabs.

**Comment by edelvarden** [comment]
> Thank you for your pull request; I have incorporated some changes as well.
> 
> There is an issue with the global_hotkey library (https://github.com/tauri-apps/global-hotkey) which prevents the registered hotkeys from functioning, hence the separate tab for search. However, I have now enabled the search functionality within the starred clipboards tab as well, and have ensured that hotkeys are disabled when you switch tabs, whether via hotkey or a click. This workaround allows for the release of the key you are typing. Until the core issue is resolved, this modification will allow for search functionality across the tabs.

Ok, thank you for feedback, but I don't quite understand about this part in SearchBar.tsx:

```tsx
<div class="absolute inset-y-0 right-2 flex items-center">
    <FaRegularImage
      class={` hover:text-indigo-600  ${
        showImages() ? "text-indigo-600" : ""
      }`}
      onClick={() => setShowImages(!showImages())}
    />
  </div>
```

Why is this needed, because if you search something images they still don't show up anyway?

How about make search more smart, eg., if search query is `text` show only text entries, if `color` show color and the same for `image` and `link`, also include text entries if content include these keywords

**Comment by 0-don** [comment]
I know you cant search for image context but I just need a simple filter button to display only images, you can make it better looking if you want and add smart search on top

**Pull request merged**
